language: csharp
mono: none
sudo: required
solution: jhray.com.sln
dist: xenial
dotnet: 2.2
addons:
 ssh_known_hosts: jhray.com
before_install:
 - bash _scripts/install.sh
script:
 - dotnet restore jhray.com.csproj
 - dotnet build jhray.com.csproj -c Release
after_success:
 - bash _scripts/deploy.sh
