language: csharp
solution: jhray.com.sln
dotnet: 2.0.0
addons:
 ssh_known_hosts: jhray.com
before_install:
 - bash _scripts/install.sh
script:
 - dotnet restore jhray.com.csproj
 - dotnet build jhray.com.csproj -c Release
after_success:
 - bash _scripts/deploy.sh
